# Setting
gpus: [0]
seed: 1
debug: False
work_dir: './work_dir'
no_progress_bar: False

# Visualization
visualization_class: 0
visualization_sample: 0
visualization_frames: []

# Data Loader
dataset: coco
dataset_args:
  coco:
    train_batch_size: 8
    eval_batch_size: 8
    path: ./data
    data_path: ./data/coco/train_data.npy
    label_path: ./data/coco/train_label.pkl
    eval_data_path: ./data/coco/val_data.npy
    eval_label_path: ./data/coco/val_label.pkl

# Model
# model_type: pa-resgcn-custom
model_type: pa-resgcn-b15
model_args:
  kernel_size: [5,2]

# Optimizer
optimizer: Adam
optimizer_args:
  Adam:
    lr: 0.0005
    betas: [0.9, 0.999]
    weight_decay: 0.0001

# Scheduler  
lr_scheduler: cosine
scheduler_args:
  cosine:
    max_epoch: 80
    warm_up: 3